mq1:
	nasm -f bin ./q1/q1.asm -o ./q1/q1.bin
	qemu-system-i386 ./q1/q1.bin

mq2:
	nasm -f bin ./q2/q2.asm -o ./q2/q2.bin
	qemu-system-i386 ./q2/q2.bin

mq3:
	nasm -f bin ./q3/q3.asm -o ./q3/q3.bin
	qemu-system-i386 ./q3/q3.bin

mq4:
	nasm -f bin ./q4/q4.asm -o ./q4/q4.bin
	qemu-system-i386 ./q4/q4.bin

mq5:
	nasm -f bin ./q5/q5.asm -o ./q5/q5.bin
	qemu-system-i386 ./q5/q5.bin