q1:
	nasm -f bin q1.asm -o q1.bin
	qemu-system-i386 q1.bin

q2:
	nasm -f bin q2.asm -o q2.bin
	qemu-system-i386 q2.bin

q3:
	nasm -f bin q3.asm -o q3.bin
	qemu-system-i386 q3.bin

q4:
	nasm -f bin q4.asm -o q4.bin
	qemu-system-i386 q4.bin

q5:
	nasm -f bin q5.asm -o q5.bin
	qemu-system-i386 q5.bin